name: Run UI tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run UI tests for Project 1
        run: dotnet test TestProject1/TestProject1.csproj --no-build --verbosity normal
        
      - name: Run UI tests for Project 2
        run: dotnet test TestProject2/TestProject2.csproj --no-build --verbosity normal
        
      - name: Run UI tests for Project 3
        run: dotnet test TestProject3/TestProject3.csproj --no-build --verbosity normal
        name: MSIX Package
        path: ${{ env.Wap_Project_Directory }}\AppPackages
